--
-- PostgreSQL database dump
--

-- Dumped from database version 14.2
-- Dumped by pg_dump version 14.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.contact_list DROP CONSTRAINT IF EXISTS contact_list_contacts_id_fk;
ALTER TABLE IF EXISTS ONLY public.address_to_contact DROP CONSTRAINT IF EXISTS address_to_contact_contacts_id_fk;
ALTER TABLE IF EXISTS ONLY public.address_to_contact DROP CONSTRAINT IF EXISTS address_to_contact_address_id_fk;
ALTER TABLE IF EXISTS ONLY public.address DROP CONSTRAINT IF EXISTS address_address_status_id_fk;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_pk;
ALTER TABLE IF EXISTS ONLY public.contacts DROP CONSTRAINT IF EXISTS contacts_pk;
ALTER TABLE IF EXISTS ONLY public.contact_list DROP CONSTRAINT IF EXISTS contact_list_pk;
ALTER TABLE IF EXISTS ONLY public.address_status DROP CONSTRAINT IF EXISTS address_status_pk;
ALTER TABLE IF EXISTS ONLY public.address DROP CONSTRAINT IF EXISTS address_pk;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.phone_number;
DROP TABLE IF EXISTS public.messengers;
DROP TABLE IF EXISTS public.contacts;
DROP TABLE IF EXISTS public.contact_list;
DROP TABLE IF EXISTS public.address_to_contact;
DROP TABLE IF EXISTS public.address_status;
DROP TABLE IF EXISTS public.address;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: address; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.address (
    id integer NOT NULL,
    address_data character varying(255),
    status character varying(4),
    status_id integer
);


ALTER TABLE public.address OWNER TO postgres;

--
-- Name: address_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: address_status; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.address_status (
    id integer NOT NULL,
    name character varying(50)
);


ALTER TABLE public.address_status OWNER TO postgres;

--
-- Name: address_status_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.address_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: address_to_contact; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.address_to_contact (
    address_id integer NOT NULL,
    recipient_id integer NOT NULL
);


ALTER TABLE public.address_to_contact OWNER TO postgres;

--
-- Name: contact_list; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contact_list (
    id integer NOT NULL,
    id_recipient integer,
    blacklist boolean
);


ALTER TABLE public.contact_list OWNER TO postgres;

--
-- Name: contact_list_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contact_list ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_list_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contacts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contacts (
    id integer NOT NULL,
    full_name character varying(255),
    birthday date,
    profession character varying(100),
    status character varying(30),
    ringtone character varying(30),
    hotkey character varying(5),
    contract_number integer,
    average_transaction_amount integer,
    discount character varying(5),
    time_to_call character varying(35),
    department character varying(40),
    "position" character varying(40),
    room_number integer,
    category character varying(15)
);


ALTER TABLE public.contacts OWNER TO postgres;

--
-- Name: contacts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contacts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contacts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messengers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messengers (
    type_messenger character varying(50),
    username character varying(100),
    id_recipient integer
);


ALTER TABLE public.messengers OWNER TO postgres;

--
-- Name: phone_number; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.phone_number (
    id integer,
    id_recipient integer,
    phone_number character varying(12),
    operator character varying(20)
);


ALTER TABLE public.phone_number OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    login character varying(50),
    password character varying(60)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: address address_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_pk PRIMARY KEY (id);


--
-- Name: address_status address_status_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address_status
    ADD CONSTRAINT address_status_pk PRIMARY KEY (id);


--
-- Name: contact_list contact_list_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contact_list
    ADD CONSTRAINT contact_list_pk PRIMARY KEY (id);


--
-- Name: contacts contacts_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT contacts_pk PRIMARY KEY (id);


--
-- Name: users users_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pk PRIMARY KEY (id);


--
-- Name: address address_address_status_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_address_status_id_fk FOREIGN KEY (status_id) REFERENCES public.address_status(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: address_to_contact address_to_contact_address_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address_to_contact
    ADD CONSTRAINT address_to_contact_address_id_fk FOREIGN KEY (address_id) REFERENCES public.address(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: address_to_contact address_to_contact_contacts_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address_to_contact
    ADD CONSTRAINT address_to_contact_contacts_id_fk FOREIGN KEY (recipient_id) REFERENCES public.contacts(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: contact_list contact_list_contacts_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contact_list
    ADD CONSTRAINT contact_list_contacts_id_fk FOREIGN KEY (id_recipient) REFERENCES public.contacts(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

