--
-- PostgreSQL database dump
--

-- Dumped from database version 14.2
-- Dumped by pg_dump version 14.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: address; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.address (
    id integer NOT NULL,
    address_data character varying(255),
    status character varying(4),
    status_id integer
);


ALTER TABLE public.address OWNER TO postgres;

--
-- Name: address_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: address_status; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.address_status (
    id integer NOT NULL,
    name character varying(50)
);


ALTER TABLE public.address_status OWNER TO postgres;

--
-- Name: address_status_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.address_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: address_to_contact; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.address_to_contact (
    address_id integer NOT NULL,
    recipient_id integer NOT NULL
);


ALTER TABLE public.address_to_contact OWNER TO postgres;

--
-- Name: contact_list; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contact_list (
    id integer NOT NULL,
    id_recipient integer,
    blacklist boolean
);


ALTER TABLE public.contact_list OWNER TO postgres;

--
-- Name: contact_list_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contact_list ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_list_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contacts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contacts (
    id integer NOT NULL,
    full_name character varying(255),
    birthday date,
    profession character varying(100),
    status character varying(30),
    ringtone character varying(30),
    hotkey character varying(5),
    contract_number integer,
    average_transaction_amount integer,
    discount character varying(5),
    time_to_call character varying(35),
    department character varying(40),
    "position" character varying(40),
    room_number integer,
    category character varying(15)
);


ALTER TABLE public.contacts OWNER TO postgres;

--
-- Name: contacts_colleagues; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contacts_colleagues (
    id integer NOT NULL,
    department character varying(40),
    "position" character varying(40),
    room_number integer
);


ALTER TABLE public.contacts_colleagues OWNER TO postgres;

--
-- Name: contacts_customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contacts_customers (
    id integer NOT NULL,
    contract_number integer,
    average_transaction_amount integer,
    discount character varying(5),
    time_to_call character varying(35)
);


ALTER TABLE public.contacts_customers OWNER TO postgres;

--
-- Name: contacts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contacts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contacts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contacts_kinsfolk; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contacts_kinsfolk (
    id integer NOT NULL,
    status character varying(30),
    ringtone character varying(30),
    hotkey integer
);


ALTER TABLE public.contacts_kinsfolk OWNER TO postgres;

--
-- Name: messengers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messengers (
    type_messenger character varying(50),
    username character varying(100),
    id_recipient integer
);


ALTER TABLE public.messengers OWNER TO postgres;

--
-- Name: phone_number; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.phone_number (
    id integer,
    id_recipient integer,
    phone_number character varying(12),
    operator character varying(20)
);


ALTER TABLE public.phone_number OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    login character varying(50),
    password character varying(60)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: address address_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_pk PRIMARY KEY (id);


--
-- Name: address_status address_status_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address_status
    ADD CONSTRAINT address_status_pk PRIMARY KEY (id);


--
-- Name: contact_list contact_list_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contact_list
    ADD CONSTRAINT contact_list_pk PRIMARY KEY (id);


--
-- Name: contacts_colleagues contacts_colleagues_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contacts_colleagues
    ADD CONSTRAINT contacts_colleagues_pk PRIMARY KEY (id);


--
-- Name: contacts_customers contacts_customers_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contacts_customers
    ADD CONSTRAINT contacts_customers_pk PRIMARY KEY (id);


--
-- Name: contacts_kinsfolk contacts_kinsfolk_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contacts_kinsfolk
    ADD CONSTRAINT contacts_kinsfolk_pk PRIMARY KEY (id);


--
-- Name: contacts contacts_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT contacts_pk PRIMARY KEY (id);


--
-- Name: users users_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pk PRIMARY KEY (id);


--
-- Name: address_address_data_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX address_address_data_idx ON public.address USING btree (status_id);


--
-- Name: address_status_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX address_status_id_idx ON public.address USING btree (status_id);


--
-- Name: address_status_name_unq; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX address_status_name_unq ON public.address_status USING btree (name);


--
-- Name: address_to_contact_address_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX address_to_contact_address_id_idx ON public.address_to_contact USING btree (address_id);


--
-- Name: address_to_contact_recipient_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX address_to_contact_recipient_id_idx ON public.address_to_contact USING btree (recipient_id);


--
-- Name: contact_list_id_recipient_unq; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX contact_list_id_recipient_unq ON public.contact_list USING btree (id_recipient);


--
-- Name: contacts_colleagues_department_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX contacts_colleagues_department_idx ON public.contacts_colleagues USING btree (department);


--
-- Name: contacts_colleagues_position_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX contacts_colleagues_position_idx ON public.contacts_colleagues USING btree ("position");


--
-- Name: contacts_colleagues_room_number_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX contacts_colleagues_room_number_idx ON public.contacts_colleagues USING btree (room_number);


--
-- Name: contacts_customers_average_transaction_amount_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX contacts_customers_average_transaction_amount_idx ON public.contacts_customers USING btree (average_transaction_amount);


--
-- Name: contacts_customers_contract_number_unq; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX contacts_customers_contract_number_unq ON public.contacts_customers USING btree (contract_number);


--
-- Name: contacts_customers_discount_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX contacts_customers_discount_idx ON public.contacts_customers USING btree (discount);


--
-- Name: contacts_customers_time_to_call_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX contacts_customers_time_to_call_idx ON public.contacts_customers USING btree (time_to_call);


--
-- Name: contacts_kinsfolk_hotkey_unq; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX contacts_kinsfolk_hotkey_unq ON public.contacts_kinsfolk USING btree (hotkey);


--
-- Name: contacts_kinsfolk_ringtone_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX contacts_kinsfolk_ringtone_idx ON public.contacts_kinsfolk USING btree (ringtone);


--
-- Name: contacts_kinsfolk_status_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX contacts_kinsfolk_status_idx ON public.contacts_kinsfolk USING btree (status);


--
-- Name: users_login_unq; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX users_login_unq ON public.users USING btree (login);


--
-- Name: address address_address_status_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_address_status_id_fk FOREIGN KEY (status_id) REFERENCES public.address_status(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: address_to_contact address_to_contact_address_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address_to_contact
    ADD CONSTRAINT address_to_contact_address_id_fk FOREIGN KEY (address_id) REFERENCES public.address(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: address_to_contact address_to_contact_contacts_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address_to_contact
    ADD CONSTRAINT address_to_contact_contacts_id_fk FOREIGN KEY (recipient_id) REFERENCES public.contacts(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: contact_list contact_list_contacts_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contact_list
    ADD CONSTRAINT contact_list_contacts_id_fk FOREIGN KEY (id_recipient) REFERENCES public.contacts(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: contacts_colleagues contacts_colleagues_contacts_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contacts_colleagues
    ADD CONSTRAINT contacts_colleagues_contacts_fk FOREIGN KEY (id) REFERENCES public.contacts(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: contacts_customers contacts_customers_contacts_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contacts_customers
    ADD CONSTRAINT contacts_customers_contacts_fk FOREIGN KEY (id) REFERENCES public.contacts(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: contacts_kinsfolk contacts_kinsfolk_contacts_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contacts_kinsfolk
    ADD CONSTRAINT contacts_kinsfolk_contacts_fk FOREIGN KEY (id) REFERENCES public.contacts(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

